spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data
    username: root
    password: iiit1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
